addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libiberty-dev
      - python3
      - python3-pip
      - zlib1g-dev

language: bash

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode10
      rvm: system
  fast_finish: true

env:
  global:
    - CODACY_PROJECT_TOKEN=c5d5d1cd62e84f38b0e77baa82d8a655
    - CODECOV_TOKEN=fb8d8ddb-9ae5-4007-9736-2b174694998d
    - PATH=${PATH}:${HOME}/kcov/bin

before_install:
- wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
- /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
- brew update && brew cask install slack
- touch custom-dark-theme.css

install:
- tar xzf master.tar.gz && cd kcov-master && mkdir build && cd build
- cmake -DCMAKE_INSTALL_PREFIX=${HOME}/kcov .. && make && sudo make install
- cd ../.. && rm -rf kcov-master && mkdir -p coverage
- mkdir -p coverage-light

jobs:
  allow_failures:
    - script: sudo kcov coverage-not-option slack-dark-mode.sh -not-an-option

script:
- sudo kcov coverage slack-dark-mode.sh
- sudo kcov coverage-light slack-dark-mode.sh --light
- sudo kcov coverage-update slack-dark-mode.sh -u

after_success:
- echo ""

after_script:
  - bash <(curl -s https://codecov.io/bash)
