addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libiberty-dev
      - python3
      - python3-pip
      - zlib1g-dev

language: bash

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode10
      rvm: system
  fast_finish: true

env:
  global:
    - CODACY_PROJECT_TOKEN=c5d5d1cd62e84f38b0e77baa82d8a655
    - CODECOV_TOKEN=fb8d8ddb-9ae5-4007-9736-2b174694998d
    - PATH=${PATH}:${HOME}/kcov/bin

before_install:
- wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
- /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
- brew update && brew cask install slack

install:
- sudo -H pip3 install -U pip && sudo -H pip3 install -U codacy-coverage
- tar xzf master.tar.gz && cd kcov-master && mkdir build && cd build
- cmake -DCMAKE_INSTALL_PREFIX=${HOME}/kcov .. && make && sudo make install
- cd ../.. && rm -rf kcov-master && mkdir -p coverage

script:
- sudo kcov coverage slack-dark-mode.sh

after_success:
- bash <(curl -s https://codecov.io/bash) && cd coverage/slack-dark-mode.sh.*
- python-codacy-coverage -r sonarqube.xml
